# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 5ca0d1b4aaf16f93c12eb7aee14624585bdd12df4ba9b3daa526bad5871a158fa0d879db344b64d7706634bd1a674a56e378f219dfb3e6e99673a251465fba0e

test:
  domain_name: example.com 
  secret_key_base: be496612b7a02ad748124bf88f4a508adf6ae109fad8c34ff45a59cb2413490965c901ee1b91e5871c5df9920d7bd1cd66de6286cac841cbe1052ad36a56ad23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
